import csv
import re

# 현재 CSV 파일 읽기
input_file = 'complete_1_to_38_pals_corrected.csv'
output_file = 'complete_1_to_42_pals.csv'

# 기존 데이터 로드
existing_data = []
with open(input_file, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        existing_data.append(row)

# 39-42번 팰 데이터
new_pals = [
    {
        "id": "39",
        "name": "핑토",
        "english_name": "Ribbuny",
        "description": "항상 방긋방긋 웃는 얼굴로 지낸다. 가끔 까부냥의 장난으로 촉수가 묶이기도 한다. 그리고 그때만큼은 귀신의 형상으로 변하게 된다고 한다.",
        "type1": "무속성",
        "type2": "",
        "rarity": "1",
        "size": "XS",
        "hp": "75",
        "melee_attack": "100",
        "shot_attack": "65",
        "defense": "70",
        "support": "100",
        "work_speed": "100",
        "male_probability": "50",
        "stamina": "100",
        "walk_speed": "100",
        "run_speed": "245",
        "ride_sprint_speed": "350",
        "slow_walk_speed": "50",
        "transport_speed": "172",
        "egg": "평범한 알",
        "gold": "1160",
        "code": "PinkRabbit",
        "genus_category": "Humanoid",
        "biological_grade": "",
        "food_amount": "2",
        "partner_skill": "야무진 손재주",
        "partner_skill_description": "보유하고 있는 동안 무속성 팰의 공격력이 증가한다. 핑토가 무기 제작대나 무기 공장 등에서 일할 때 작업 효율이 향상된다.",
        "partner_skill_level_1": "작업 속도 +200% (ToSelf), 공격 +10% (ToSelf)",
        "work_suitability_1": "수작업 Lv1",
        "work_suitability_2": "채집 Lv1",
        "work_suitability_3": "운반 Lv1",
        "work_suitability_4": "",
        "active_skill_1": "공기 대포 (무속성, 위력: 25, 쿨타임: 2)",
        "active_skill_2": "파워 샷 (무속성, 위력: 35, 쿨타임: 4)",
        "active_skill_3": "얼음 미사일 (얼음 속성, 위력: 30, 쿨타임: 3)",
        "active_skill_4": "눈보라 스파이크 (얼음 속성, 위력: 130, 쿨타임: 45)",
        "active_skill_5": "파워 폭탄 (무속성, 위력: 70, 쿨타임: 15)",
        "active_skill_6": "빙산 (얼음 속성, 위력: 70, 쿨타임: 15)",
        "active_skill_7": "팰 폭발 (무속성, 위력: 150, 쿨타임: 55)",
        "drop_item_1": "가죽 (100%)",
        "drop_item_2": "예쁜 꽃 (5%)",
        "drop_item_3": "핑토의 리본 (50%)",
        "capture_rate": "1"
    },
    {
        "id": "40",
        "name": "헬고트",
        "english_name": "Incineram",
        "description": "밤에 사냥감을 잡아 자기 영역에 돌아온다. 잡힌 팰이 그 후 어떤 일을 당할지는 불 보듯 뻔하다.",
        "type1": "화염",
        "type2": "어둠",
        "rarity": "4",
        "size": "M",
        "hp": "95",
        "melee_attack": "150",
        "shot_attack": "100",
        "defense": "85",
        "support": "100",
        "work_speed": "100",
        "male_probability": "50",
        "stamina": "100",
        "walk_speed": "160",
        "run_speed": "700",
        "ride_sprint_speed": "960",
        "slow_walk_speed": "80",
        "transport_speed": "320",
        "egg": "열기 나는 알",
        "gold": "4780",
        "code": "Baphomet",
        "genus_category": "Humanoid",
        "biological_grade": "4",
        "food_amount": "4",
        "partner_skill": "화염 발톱의 사냥꾼",
        "partner_skill_description": "발동하면 목표로 삼은 적을 향해 높은 위력의 지옥불 할퀴기로 공격한다.",
        "partner_skill_level_1": "지옥불 할퀴기 1.1배",
        "work_suitability_1": "불 피우기 Lv1",
        "work_suitability_2": "수작업 Lv2",
        "work_suitability_3": "채굴 Lv1",
        "work_suitability_4": "운반 Lv2",
        "active_skill_1": "파이어 샷 (화염 속성, 위력: 30, 쿨타임: 2)",
        "active_skill_2": "스피릿 파이어 (화염 속성, 위력: 45, 쿨타임: 7)",
        "active_skill_3": "불화살 (화염 속성, 위력: 55, 쿨타임: 10)",
        "active_skill_4": "지옥불 할퀴기 (화염 속성, 위력: 70, 쿨타임: 10)",
        "active_skill_5": "그림자 폭발 (어둠 속성, 위력: 55, 쿨타임: 10)",
        "active_skill_6": "화염구 (화염 속성, 위력: 150, 쿨타임: 55)",
        "active_skill_7": "인페르노 (화염 속성, 위력: 120, 쿨타임: 40)",
        "drop_item_1": "뿔 (100%)",
        "drop_item_2": "가죽 (100%)",
        "drop_item_3": "",
        "capture_rate": "1"
    },
    {
        "id": "41",
        "name": "귀요비",
        "english_name": "Cinnamoth",
        "description": "가루를 흡입하면 승천하는 듯한 쾌락을 안겨준다. 단속을 강화하자는 움직임도 있지만 팰 애호 단체의 반대로 진척이 없다.",
        "type1": "풀",
        "type2": "",
        "rarity": "4",
        "size": "M",
        "hp": "70",
        "melee_attack": "100",
        "shot_attack": "80",
        "defense": "80",
        "support": "100",
        "work_speed": "100",
        "male_probability": "50",
        "stamina": "100",
        "walk_speed": "150",
        "run_speed": "550",
        "ride_sprint_speed": "700",
        "slow_walk_speed": "30",
        "transport_speed": "350",
        "egg": "신록의 알",
        "gold": "5700",
        "code": "CuteButterfly",
        "genus_category": "Bird",
        "biological_grade": "",
        "food_amount": "3",
        "partner_skill": "수수께끼의 비늘 가루",
        "partner_skill_description": "발동하면 목표로 삼은 적을 향해 독 안개로 공격한다.",
        "partner_skill_level_1": "독 안개 1.1배",
        "work_suitability_1": "파종 Lv2",
        "work_suitability_2": "제약 Lv1",
        "work_suitability_3": "",
        "work_suitability_4": "",
        "active_skill_1": "공기 대포 (무속성, 위력: 25, 쿨타임: 2)",
        "active_skill_2": "바람의 칼날 (풀 속성, 위력: 30, 쿨타임: 2)",
        "active_skill_3": "독 안개 (어둠 속성, 위력: 0, 쿨타임: 30)",
        "active_skill_4": "모래 폭풍 (땅 속성, 위력: 80, 쿨타임: 18)",
        "active_skill_5": "씨앗 지뢰 (풀 속성, 위력: 65, 쿨타임: 13)",
        "active_skill_6": "초록 폭풍 (풀 속성, 위력: 80, 쿨타임: 18)",
        "active_skill_7": "태양 폭발 (풀 속성, 위력: 150, 쿨타임: 55)",
        "drop_item_1": "벌꿀 (100%)",
        "drop_item_2": "양상추 씨 (20%)",
        "drop_item_3": "밀 씨 (20%)",
        "capture_rate": "1"
    },
    {
        "id": "42",
        "name": "불페르노",
        "english_name": "Arsox",
        "description": "먼 옛날엔 육식 팰에게 사냥당하기 일쑤였다. 그 부조리에 울부짖은 불페르노 무리의 분노는 활활 타오르며 대대로 이어졌다.",
        "type1": "화염",
        "type2": "",
        "rarity": "4",
        "size": "M",
        "hp": "85",
        "melee_attack": "100",
        "shot_attack": "95",
        "defense": "95",
        "support": "100",
        "work_speed": "100",
        "male_probability": "50",
        "stamina": "120",
        "walk_speed": "87",
        "run_speed": "700",
        "ride_sprint_speed": "1050",
        "slow_walk_speed": "87",
        "transport_speed": "343",
        "egg": "열기 나는 알",
        "gold": "3520",
        "code": "FlameBuffalo",
        "genus_category": "FourLegged",
        "biological_grade": "3",
        "food_amount": "5",
        "partner_skill": "따끈따끈 육체",
        "partner_skill_description": "등에 타고 이동할 수 있다. 탑승 중에는 따뜻하여 추위를 느끼지 않게 된다.",
        "partner_skill_level_1": "추위 무효화 (ToTrainer)",
        "work_suitability_1": "불 피우기 Lv2",
        "work_suitability_2": "벌목 Lv1",
        "work_suitability_3": "",
        "work_suitability_4": "",
        "active_skill_1": "파이어 샷 (화염 속성, 위력: 30, 쿨타임: 2)",
        "active_skill_2": "불타는 뿔 (화염 속성, 위력: 50, 쿨타임: 9)",
        "active_skill_3": "스피릿 파이어 (화염 속성, 위력: 45, 쿨타임: 7)",
        "active_skill_4": "불화살 (화염 속성, 위력: 55, 쿨타임: 10)",
        "active_skill_5": "파이어 브레스 (화염 속성, 위력: 70, 쿨타임: 15)",
        "active_skill_6": "인페르노 (화염 속성, 위력: 120, 쿨타임: 40)",
        "active_skill_7": "화염구 (화염 속성, 위력: 150, 쿨타임: 55)",
        "drop_item_1": "뿔 (100%)",
        "drop_item_2": "발화 기관 (100%)",
        "drop_item_3": "",
        "capture_rate": "1"
    }
]

# 기존 데이터에 새 팰 추가
all_data = existing_data + new_pals

# 새 CSV 파일에 저장
with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(all_data)

print(f"✅ 완료! {output_file} 저장됨")
print(f"총 {len(all_data)}개 팰")
print(f"- 기존 1-38번: {len(existing_data)}개")
print(f"- 새로 추가 39-42번: {len(new_pals)}개")
print(f"컬럼 수: {len(fieldnames)}") 