import csv
import re

# 현재 CSV 파일 읽기
input_file = 'complete_1_to_46_pals.csv'
output_file = 'complete_1_to_48_pals.csv'

# 기존 데이터 로드
existing_data = []
with open(input_file, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        existing_data.append(row)

# 44-48번 팰 데이터 (정확한 필드명 사용)
new_pals = [
    {
        "id": "44",
        "name_kor": "마스크로우",
        "description_kor": "원래 드넓은 창공을 자유로이 날아다녔으나 질풍수리와(과) 싸움에서 패배해 하늘을 빼앗기고 밤에 숨죽인 채 살게 됐다.",
        "elements": "어둠",
        "partnerSkill_name": "원격 부리 공격",
        "partnerSkill_describe": "발동하면 목표로 삼은 적을 향해 높은 위력의 팬텀의 공격(으)로 공격한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "partnerSkill_skillNames": "[팬텀의 공격]",
        "partnerSkill_cooltime": "",
        "paldeck_number": "44",
        "rarity": "3",
        "type": "조류",
        "size": "M",
        "hp": "75",
        "melee_attack": "80",
        "shot_attack": "95",
        "defense": "80",
        "support": "100",
        "work_speed": "100",
        "food": "5",
        "walking_speed": "170",
        "running_speed": "920",
        "ride_sprint_speed": "1200",
        "transport_speed": "545",
        "male_probability": "50",
        "nocturnal": "1",
        "work_lumbering": "1",
        "work_handiwork": "0",
        "work_transporting": "0",
        "work_kindling": "0",
        "work_planting": "0",
        "work_watering": "0",
        "work_harvesting": "0",
        "work_gathering": "0",
        "work_mining": "0",
        "work_oil_extraction": "0",
        "work_electricity": "0",
        "work_medicine_production": "0",
        "work_cooling": "0",
        "work_farming": "0",
        "active_skills": "공기 대포(Lv.1)|암흑구(Lv.7)|팬텀의 공격(Lv.15)|그림자 폭발(Lv.22)|유령의 불꽃(Lv.30)|악몽의 구체(Lv.40)|어둠의 레이저(Lv.50)",
        "drops": "뼈 2–4(100%)|독샘 2(100%)|작은 팰 영혼 1(1%)",
        "breeding_rank": "1080",
        "price": "1840",
        "craft_speed": "0"
    },
    {
        "id": "45",
        "name_kor": "도마맨",
        "description_kor": "일어선 모습에 이상한 집착을 보인다. 항상 제일 멋진 자세를 연구하며 거울을 주면 하루 종일 자세만 궁리한다.",
        "elements": "어둠",
        "partnerSkill_name": "제6감",
        "partnerSkill_describe": "발동하면 6번째 감각을 활용해 가까이 있는 던전의 위치를 탐지할 수 있다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "partnerSkill_skillNames": "[SearchDungeon]",
        "partnerSkill_cooltime": "60",
        "paldeck_number": "45",
        "rarity": "2",
        "type": "인간형",
        "size": "S",
        "hp": "80",
        "melee_attack": "90",
        "shot_attack": "80",
        "defense": "50",
        "support": "100",
        "work_speed": "100",
        "food": "3",
        "walking_speed": "140",
        "running_speed": "600",
        "ride_sprint_speed": "800",
        "transport_speed": "270",
        "male_probability": "50",
        "nocturnal": "1",
        "work_lumbering": "0",
        "work_handiwork": "1",
        "work_transporting": "1",
        "work_kindling": "0",
        "work_planting": "0",
        "work_watering": "0",
        "work_harvesting": "0",
        "work_gathering": "1",
        "work_mining": "0",
        "work_oil_extraction": "0",
        "work_electricity": "0",
        "work_medicine_production": "0",
        "work_cooling": "0",
        "work_farming": "0",
        "active_skills": "독 사격(Lv.1)|암흑구(Lv.7)|그림자 폭발(Lv.15)|유령의 불꽃(Lv.22)|악몽의 구체(Lv.30)|파이어 브레스(Lv.40)|어둠의 레이저(Lv.50)",
        "drops": "구리 열쇠 1(100%)|은 열쇠 1(1%)|도마맨의 볏 1(50%)",
        "breeding_rank": "1120",
        "price": "1720",
        "craft_speed": "0"
    },
    {
        "id": "46",
        "name_kor": "달서니",
        "description_kor": "머리의 뿔은 달빛을 받아야 자란다. 태양을 못 견디는 건 아니지만 햇빛을 쬐는 동안에는 뿔이 근질거린다.",
        "elements": "어둠",
        "partnerSkill_name": "어둠 속에 번쩍이는 발톱날",
        "partnerSkill_describe": "발동하면 목표로 삼은 적을 향해 높은 위력의 점프 할퀴기(으)로 공격한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "partnerSkill_skillNames": "[점프 할퀴기]",
        "partnerSkill_cooltime": "",
        "paldeck_number": "46",
        "rarity": "3",
        "type": "인간형",
        "size": "M",
        "hp": "80",
        "melee_attack": "130",
        "shot_attack": "100",
        "defense": "80",
        "support": "100",
        "work_speed": "100",
        "food": "5",
        "walking_speed": "175",
        "running_speed": "600",
        "ride_sprint_speed": "800",
        "transport_speed": "375",
        "male_probability": "50",
        "nocturnal": "1",
        "work_lumbering": "0",
        "work_handiwork": "2",
        "work_transporting": "0",
        "work_kindling": "0",
        "work_planting": "0",
        "work_watering": "0",
        "work_harvesting": "0",
        "work_gathering": "0",
        "work_mining": "0",
        "work_oil_extraction": "0",
        "work_electricity": "0",
        "work_medicine_production": "0",
        "work_cooling": "0",
        "work_farming": "0",
        "active_skills": "암흑구(Lv.1)|점프 할퀴기(Lv.7)|그림자 폭발(Lv.15)|얼음 칼날(Lv.22)|유령의 불꽃(Lv.30)|악몽의 구체(Lv.40)|어둠의 레이저(Lv.50)",
        "drops": "뼈 1(100%)",
        "breeding_rank": "950",
        "price": "2400",
        "craft_speed": "0"
    },
    {
        "id": "47",
        "name_kor": "질풍수리",
        "description_kor": "사람을 낚아챈 채로도 잘 날아다닌다. 하지만 지치면 주저 없이 놓아버리므로 추락사 사고가 끊이지 않는다.",
        "elements": "무속성",
        "partnerSkill_name": "질풍의 활공",
        "partnerSkill_describe": "보유하고 있는 동안 글라이더의 성능이 변화한다. 활공 속도가 증가하며, 오른손으로 사격이 가능해진다.",
        "partnerSkill_needItem": "질풍수리의 장갑",
        "partnerSkill_needItemTechLevel": "23",
        "partnerSkill_level": "1",
        "partnerSkill_skillNames": "[글라이더 강화]",
        "partnerSkill_cooltime": "",
        "paldeck_number": "47",
        "rarity": "2",
        "type": "조류",
        "size": "M",
        "hp": "75",
        "melee_attack": "120",
        "shot_attack": "85",
        "defense": "60",
        "support": "100",
        "work_speed": "100",
        "food": "4",
        "walking_speed": "200",
        "running_speed": "600",
        "ride_sprint_speed": "700",
        "transport_speed": "400",
        "male_probability": "50",
        "nocturnal": "0",
        "work_lumbering": "0",
        "work_handiwork": "0",
        "work_transporting": "0",
        "work_kindling": "0",
        "work_planting": "0",
        "work_watering": "0",
        "work_harvesting": "0",
        "work_gathering": "2",
        "work_mining": "0",
        "work_oil_extraction": "0",
        "work_electricity": "0",
        "work_medicine_production": "0",
        "work_cooling": "0",
        "work_farming": "0",
        "active_skills": "활공 할퀴기(Lv.1)|공기 대포(Lv.7)|모래 돌풍(Lv.15)|바람의 칼날(Lv.22)|모래 폭풍(Lv.30)|초록 폭풍(Lv.40)|팰 폭발(Lv.50)",
        "drops": "질풍수리의 살코기 1(100%)|가죽 1(100%)",
        "breeding_rank": "1030",
        "price": "2010",
        "craft_speed": "0"
    },
    {
        "id": "48",
        "name_kor": "로빈몽",
        "description_kor": "숲에서 수렵 생활을 하는, 사람과 비슷한 성질의 팰. 아주 먼 옛날 사람과 다른 계통으로 갈라졌다고 여겨지며 팰의 정체를 밝혀줄 열쇠일지도 모른다.",
        "elements": "풀",
        "partnerSkill_name": "매의 눈",
        "partnerSkill_describe": "함께 싸우는 동안 플레이어가 약점 부위에 주는 피해량이 증가한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "partnerSkill_skillNames": "[약점 피해 증가]",
        "partnerSkill_cooltime": "",
        "paldeck_number": "48",
        "rarity": "5",
        "type": "인간형",
        "size": "M",
        "hp": "90",
        "melee_attack": "100",
        "shot_attack": "105",
        "defense": "80",
        "support": "100",
        "work_speed": "100",
        "food": "3",
        "walking_speed": "100",
        "running_speed": "600",
        "ride_sprint_speed": "750",
        "transport_speed": "400",
        "male_probability": "50",
        "nocturnal": "0",
        "work_lumbering": "1",
        "work_handiwork": "2",
        "work_transporting": "2",
        "work_kindling": "0",
        "work_planting": "1",
        "work_watering": "0",
        "work_harvesting": "0",
        "work_gathering": "2",
        "work_mining": "0",
        "work_oil_extraction": "0",
        "work_electricity": "0",
        "work_medicine_production": "1",
        "work_cooling": "0",
        "work_farming": "0",
        "active_skills": "바람의 칼날(Lv.1)|파워 샷(Lv.7)|스나이핑 샷(Lv.15)|씨앗 지뢰(Lv.22)|초록 폭풍(Lv.30)|가시덩굴(Lv.40)|태양 폭발(Lv.50)",
        "drops": "밀 씨 1–2(50%)|화살 2–4(100%)|감자 종자 1(50%)",
        "breeding_rank": "1020",
        "price": "2050",
        "craft_speed": "0"
    }
]

# 새로운 CSV 파일 생성
with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    
    # 기존 데이터 쓰기
    writer.writerows(existing_data)
    
    # 새로운 팰 데이터 쓰기
    writer.writerows(new_pals)

print(f"✅ 완료! {output_file} 저장됨")
print(f"총 {len(existing_data) + len(new_pals)}개 팰")
print(f"- 기존 1-46번 (43,49,50,51번 포함): {len(existing_data)}개")  
print(f"- 새로 추가 44-48번: {len(new_pals)}개")
print(f"컬럼 수: {len(fieldnames)}") 