import csv
import re

# 현재 CSV 파일 읽기
input_file = 'complete_1_to_48_pals.csv'
output_file = 'complete_1_to_56_pals.csv'

# 기존 데이터 로드
existing_data = []
with open(input_file, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        existing_data.append(row)

# 52-56번 팰 데이터 (정확한 필드명 사용)
new_pals = [
    {
        "id": "52",
        "name_kor": "소름냥이",
        "description_kor": "쥐구멍을 찾아다니며 무언가를 쫓고 있다. 몇 년에 걸친 관찰 결과 그것은 '소름'이라는 것이 밝혀졌다.",
        "elements": "무속성",
        "partnerSkill_name": "소름냥이의 실수",
        "partnerSkill_describe": "보유하고 있는 동안 무속성 팰의 공격력이 증가한다. 가끔 작업 중 아이템을 발견하기도 한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "stats_size": "S",
        "stats_rarity": "1",
        "stats_health": "60",
        "stats_food": "150",
        "stats_meleeAttack": "100",
        "stats_attack": "70",
        "stats_defense": "70",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "1.1",
        "stats_maleProbability": "50",
        "stats_combiRank": "1540",
        "stats_goldCoin": "1460",
        "stats_egg": "평범한 알",
        "stats_code": "Grintale",
        "movement_slowWalkSpeed": "70",
        "movement_walkSpeed": "110",
        "movement_runSpeed": "300",
        "movement_rideSprintSpeed": "",
        "movement_transportSpeed": "",
        "level60_health": "2775-3360",
        "level60_attack": "441-543",
        "level60_defense": "391-493",
        "activeSkills": "공기 대포(무속성, 25파워, 2초) | 윈드 커터(풀속성, 30파워, 3초) | 파워 샷(무속성, 35파워, 4초) | 파워 폭탄(무속성, 70파워, 15초) | 코큰트 불릿(무속성, 150파워, 55초) | 윈드 블래스트(풀속성, 80파워, 12초) | 팰 폭발(무속성, 150파워, 55초)",
        "activeSkills_count": "7",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "양털(1, 100%) | 소름냥이의 털털털(1, 50%)",
        "drops_count": "2",
        "workSuitabilities": "수작업(LV.1) | 운반(LV.1) | 채굴(LV.1)",
        "workSuitabilities_count": "3",
        "tribes": "소름냥이",
        "tribes_count": "1",
        "spawners": "소름냥이(Lv. 20-22)",
        "spawners_count": "1"
    },
    {
        "id": "53",
        "name_kor": "모프링",
        "description_kor": "지면을 기어 다니며 미세 유기물을 섭취한다. 영양이 없는 건 잠시 후 배출한다. 걸레라 생각하고 청소에 활용하면 서로 윈윈.",
        "elements": "얼음",
        "partnerSkill_name": "복슬복슬",
        "partnerSkill_describe": "보유하고 있는 동안 모프킹의 스테이터스가 상승한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "stats_size": "XS",
        "stats_rarity": "1",
        "stats_health": "60",
        "stats_food": "150",
        "stats_meleeAttack": "100",
        "stats_attack": "60",
        "stats_defense": "60",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "1.1",
        "stats_maleProbability": "50",
        "stats_combiRank": "1300",
        "stats_goldCoin": "1180",
        "stats_egg": "얼어붙은 알",
        "stats_code": "MopBaby",
        "movement_slowWalkSpeed": "55",
        "movement_walkSpeed": "100",
        "movement_runSpeed": "250",
        "movement_rideSprintSpeed": "400",
        "movement_transportSpeed": "175",
        "level60_health": "2775-3360",
        "level60_attack": "392-480",
        "level60_defense": "342-430",
        "activeSkills": "공기 대포(무속성, 25파워, 2초) | 얼음 미사일(얼음 속성, 30파워, 3초) | 얼음 칼날(얼음 속성, 55파워, 10초) | 파워 폭탄(무속성, 70파워, 15초) | 빙산(얼음 속성, 70파워, 15초) | 서리 낀 입김(얼음 속성, 90파워, 22초) | 눈보라 스파이크(얼음 속성, 130파워, 45초)",
        "activeSkills_count": "7",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "양털(1, 100%) | 모프링의 솜털(1, 50%)",
        "drops_count": "2",
        "workSuitabilities": "채집(LV.1) | 냉각(LV.1)",
        "workSuitabilities_count": "2",
        "tribes": "수수께끼의 복슬복슬한 모프링 | 모프링",
        "tribes_count": "2",
        "spawners": "모프링(Lv. 12-14) | 모프링(Lv. 10-12) | 모프링(Lv. 20-27) | 모프링(Lv. 14-17, 계곡의 동굴)",
        "spawners_count": "4"
    },
    {
        "id": "54",
        "name_kor": "모프킹",
        "description_kor": "동면 중엔 거대한 털 뭉치 속에 대량의 모프링이 숨어 있다. 과거 최대 기록은 무려 101마리.",
        "elements": "얼음",
        "partnerSkill_name": "복슬복슬 끝판왕",
        "partnerSkill_describe": "등에 타고 이동할 수 있다. 함께 싸우는 동안 보유하고 있는 모프링의 개체수가 많을수록 스테이터스가 상승한다.",
        "partnerSkill_needItem": "모프킹 안장",
        "partnerSkill_needItemTechLevel": "14",
        "partnerSkill_level": "1",
        "stats_size": "L",
        "stats_rarity": "6",
        "stats_health": "100",
        "stats_food": "225",
        "stats_meleeAttack": "100",
        "stats_attack": "90",
        "stats_defense": "90",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "1",
        "stats_maleProbability": "50",
        "stats_combiRank": "410",
        "stats_goldCoin": "6400",
        "stats_egg": "얼어붙은 대형 알",
        "stats_code": "MopKing",
        "movement_slowWalkSpeed": "60",
        "movement_walkSpeed": "120",
        "movement_runSpeed": "650",
        "movement_rideSprintSpeed": "1020",
        "movement_transportSpeed": "210",
        "level60_health": "4075-5050",
        "level60_attack": "538-670",
        "level60_defense": "488-620",
        "activeSkills": "파워 샷(무속성, 35파워, 4초) | 얼음 미사일(얼음 속성, 30파워, 3초) | 얼음 칼날(얼음 속성, 55파워, 10초) | 빙산(얼음 속성, 70파워, 15초) | 서리 낀 입김(얼음 속성, 90파워, 22초) | 팰 폭발(무속성, 150파워, 55초) | 눈보라 스파이크(얼음 속성, 130파워, 45초)",
        "activeSkills_count": "7",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "양털(3-5, 100%)",
        "drops_count": "1",
        "workSuitabilities": "채집(LV.2) | 냉각(LV.2)",
        "workSuitabilities_count": "2",
        "tribes": "수수께끼 복슬복슬 왕 모프킹 | 모프킹",
        "tribes_count": "2",
        "spawners": "모프킹(Lv. 15-18) | 모프킹(Lv. 28-32) | 수수께끼 복슬복슬 왕 모프킹(Lv. 17-19, 계곡의 동굴)",
        "spawners_count": "3"
    },
    {
        "id": "55",
        "name_kor": "베비뇽",
        "description_kor": "몸을 둥글게 말아 엄청난 속도로 회전 이동할 수 있다. 옛날 사람들은 길들인 베비뇽에게 우유 주머니를 달아 방목하며 그 회전력으로 버터를 만들었다.",
        "elements": "얼음|용",
        "partnerSkill_name": "꿈틀꿈틀 족제비",
        "partnerSkill_describe": "등에 타고 이동할 수 있다. 탑승 중 플레이어의 공격이 용 속성으로 변화한다.",
        "partnerSkill_needItem": "베비뇽 안장",
        "partnerSkill_needItemTechLevel": "13",
        "partnerSkill_level": "1",
        "stats_size": "M",
        "stats_rarity": "4",
        "stats_health": "90",
        "stats_food": "225",
        "stats_meleeAttack": "100",
        "stats_attack": "80",
        "stats_defense": "80",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "1",
        "stats_maleProbability": "50",
        "stats_combiRank": "800",
        "stats_goldCoin": "3450",
        "stats_egg": "얼어붙은 알",
        "stats_code": "WeaselDragon",
        "movement_slowWalkSpeed": "100",
        "movement_walkSpeed": "180",
        "movement_runSpeed": "750",
        "movement_rideSprintSpeed": "1050",
        "movement_transportSpeed": "390",
        "level60_health": "3750-4627",
        "level60_attack": "490-607",
        "level60_defense": "440-557",
        "activeSkills": "얼음 미사일(얼음 속성, 30파워, 3초) | 용 대포(용 속성, 30파워, 2초) | 로켓 태클(용 속성, 50파워, 6초) | 용의 파장(용 속성, 55파워, 10초) | 얼음 칼날(얼음 속성, 55파워, 10초) | 용의 숨결(용 속성, 70파워, 15초) | 서리 낀 입김(얼음 속성, 90파워, 22초) | 용의 운석(용 속성, 150파워, 55초)",
        "activeSkills_count": "8",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "가죽(2-3, 100%)",
        "drops_count": "1",
        "workSuitabilities": "채집(LV.1) | 냉각(LV.1)",
        "workSuitabilities_count": "2",
        "tribes": "초원의 무희 베비뇽 | 베비뇽 | 천도뇽",
        "tribes_count": "3",
        "spawners": "베비뇽(Lv. 20-28) | 베비뇽(Lv. 36-39) | 초원의 무희 베비뇽(Lv. 42-45, 영봉의 동굴) | 베비뇽(Lv. 39-41, 영봉의 동굴)",
        "spawners_count": "4"
    },
    {
        "id": "56",
        "name_kor": "썬더콘",
        "description_kor": "예전엔 번개 신의 사자로 여겨져 사람들이 건드리지 않았다. 하지만 낙뢰에 맞아 사망하는 모습이 목격된 뒤로 신앙이 무너지며 보이는 족족 잡혔다.",
        "elements": "번개",
        "partnerSkill_name": "질풍과 우레",
        "partnerSkill_describe": "등에 타고 이동할 수 있다. 탑승 중 플레이어의 공격이 번개 속성으로 변화한다.",
        "partnerSkill_needItem": "썬더콘 안장",
        "partnerSkill_needItemTechLevel": "14",
        "partnerSkill_level": "1",
        "stats_size": "M",
        "stats_rarity": "5",
        "stats_health": "80",
        "stats_food": "350",
        "stats_meleeAttack": "110",
        "stats_attack": "105",
        "stats_defense": "105",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "0.9",
        "stats_maleProbability": "50",
        "stats_combiRank": "680",
        "stats_goldCoin": "4280",
        "stats_egg": "찌릿찌릿한 대형 알",
        "stats_code": "Kirin",
        "movement_slowWalkSpeed": "80",
        "movement_walkSpeed": "130",
        "movement_runSpeed": "720",
        "movement_rideSprintSpeed": "1100",
        "movement_transportSpeed": "425",
        "level60_health": "3425-4205",
        "level60_attack": "611-765",
        "level60_defense": "561-715",
        "activeSkills": "스파크 샷(번개 속성, 30파워, 2초) | 전기 파장(번개 속성, 40파워, 4초) | 질풍뇌격(번개 속성, 60파워, 8초) | 고정식 레이저(번개 속성, 70파워, 15초) | 라인 썬더(번개 속성, 75파워, 16초) | 트라이 썬더(번개 속성, 90파워, 22초) | 번개 일격(번개 속성, 120파워, 40초) | 전기 볼트(번개 속성, 150파워, 55초)",
        "activeSkills_count": "8",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "가죽(2, 100%) | 발전 기관(1, 100%) | 뿔(1, 50%)",
        "drops_count": "3",
        "workSuitabilities": "발전(LV.2) | 벌목(LV.1)",
        "workSuitabilities_count": "2",
        "tribes": "질풍 우레 썬더콘 | 썬더콘",
        "tribes_count": "2",
        "spawners": "썬더콘(Lv. 13-17) | 질풍 우레 썬더콘(Lv. 17-19, 계곡의 동굴) | 썬더콘(Lv. 14-17, 계곡의 동굴)",
        "spawners_count": "3"
    }
]

# 모든 데이터 합치기
all_data = existing_data + new_pals

# 새 CSV 파일로 저장
with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(all_data)

print(f"✅ 완료! {output_file} 저장됨")
print(f"총 {len(all_data)}개 팰 (기존 {len(existing_data)}개 + 새로 추가된 {len(new_pals)}개)")
print(f"컬럼 수: {len(fieldnames)}") 