#!/usr/bin/env python3

import csv
from pathlib import Path

def main():
    # 기존 CSV 파일 읽기
    input_file = 'complete_1_to_60_pals.csv'
    output_file = 'complete_1_to_64_pals.csv'
    
    if not Path(input_file).exists():
        print(f"Error: {input_file} not found!")
        return
    
    # 61-64번 팰 데이터
    new_pals = [
        {
            'id': 61,
            'name_kor': '불이리',
            'description_kor': '기질이 워낙 예민해 기분이 상하면 동굴에 숨어 버린다. 옛 사람들은 불이리가 숨으면 흉조로 여겼다.',
            'elements': 'Fire',
            'partnerSkill_name': '무념무상',
            'partnerSkill_describe': '등에 타고 이동할 수 있다. 탑승 중에는 추위나 더위의 영향을 받지 않는다.',
            'partnerSkill_needItem': '',
            'partnerSkill_needItemTechLevel': '',
            'partnerSkill_level': '',
            'stats_size': 'M',
            'stats_rarity': 6,
            'stats_health': 100,
            'stats_food': 4,
            'stats_meleeAttack': 70,
            'stats_attack': 115,
            'stats_defense': 100,
            'stats_workSpeed': 100,
            'stats_support': 110,
            'stats_captureRateCorrect': 1,
            'stats_maleProbability': 50,
            'stats_combiRank': 830,
            'stats_gold': 3170,
            'stats_slowWalkSpeed': 80,
            'stats_walkSpeed': 130,
            'stats_runSpeed': 700,
            'stats_rideSprintSpeed': 1100,
            'stats_transportSpeed': 415,
            'stats_stamina': 140,
            'work_kindling': 2,
            'work_watering': 0,
            'work_planting': 0,
            'work_generating_electricity': 0,
            'work_handiwork': 0,
            'work_gathering': 0,
            'work_lumbering': 0,
            'work_mining': 0,
            'work_medicine': 0,
            'work_cooling': 0,
            'work_transporting': 0,
            'work_farming': 0,
            'active_skill_1': '파이어 샷',
            'active_skill_2': '스피릿 파이어',
            'active_skill_3': '유령의 불꽃',
            'active_skill_4': '풍림화산',
            'active_skill_5': '화염 폭풍',
            'active_skill_6': '인페르노',
            'active_skill_7': '화염구',
            'drops': '발화 기관|가죽',
            'nickname': '',
            'map_daytime': 0,
            'map_nighttime': 17
        },
        {
            'id': 62,
            'name_kor': '썬더 키드',
            'description_kor': '외톨이인 팰에게 친근하게 잘 대해준다. 착각한 상대 팰이 곁을 내주기가 무섭게 이때다 하고 낙뢰로 숨통을 끊는다.',
            'elements': 'Electric',
            'partnerSkill_name': '천둥의 딸',
            'partnerSkill_describe': '보유하고 있는 동안 플레이어 가까이에 출현한다. 플레이어의 공격에 맞춰 낙뢰로 추격한다.',
            'partnerSkill_needItem': '',
            'partnerSkill_needItemTechLevel': '',
            'partnerSkill_level': '',
            'stats_size': 'XS',
            'stats_rarity': 2,
            'stats_health': 70,
            'stats_food': 2,
            'stats_meleeAttack': 110,
            'stats_attack': 80,
            'stats_defense': 70,
            'stats_workSpeed': 100,
            'stats_support': 100,
            'stats_captureRateCorrect': 1,
            'stats_maleProbability': 20,
            'stats_combiRank': 1210,
            'stats_gold': 1390,
            'stats_slowWalkSpeed': 120,
            'stats_walkSpeed': 200,
            'stats_runSpeed': 400,
            'stats_rideSprintSpeed': 550,
            'stats_transportSpeed': 300,
            'stats_stamina': 100,
            'work_kindling': 0,
            'work_watering': 0,
            'work_planting': 0,
            'work_generating_electricity': 1,
            'work_handiwork': 1,
            'work_gathering': 0,
            'work_lumbering': 0,
            'work_mining': 0,
            'work_medicine': 0,
            'work_cooling': 0,
            'work_transporting': 1,
            'work_farming': 0,
            'active_skill_1': '공기 대포',
            'active_skill_2': '전기 파장',
            'active_skill_3': '산성비',
            'active_skill_4': '라인 썬더',
            'active_skill_5': '트라이 썬더',
            'active_skill_6': '번개 일격',
            'active_skill_7': '전기 볼트',
            'drops': '발전 기관|썬더키드의 구름',
            'nickname': '',
            'map_daytime': 501,
            'map_nighttime': 501
        },
        {
            'id': 63,
            'name_kor': '루나리스',
            'description_kor': '무심결에 눈을 쳐다봤다간 꼼짝없이 당하고 만다. 루나리스를 데리고 다니는 상당수는 그저 그렇게 하도록 홀렸을 뿐이다.',
            'elements': 'Neutral',
            'partnerSkill_name': '반중력',
            'partnerSkill_describe': '보유하고 있는 동안 루나리스의 반중력에 의해 플레이어의 소지 중량 제한이 증가한다.',
            'partnerSkill_needItem': '',
            'partnerSkill_needItemTechLevel': '',
            'partnerSkill_level': '',
            'stats_size': 'M',
            'stats_rarity': 6,
            'stats_health': 90,
            'stats_food': 2,
            'stats_meleeAttack': 80,
            'stats_attack': 100,
            'stats_defense': 90,
            'stats_workSpeed': 100,
            'stats_support': 100,
            'stats_captureRateCorrect': 1,
            'stats_maleProbability': 50,
            'stats_combiRank': 1110,
            'stats_gold': 1760,
            'stats_slowWalkSpeed': 80,
            'stats_walkSpeed': 130,
            'stats_runSpeed': 500,
            'stats_rideSprintSpeed': 650,
            'stats_transportSpeed': 315,
            'stats_stamina': 100,
            'work_kindling': 0,
            'work_watering': 0,
            'work_planting': 0,
            'work_generating_electricity': 0,
            'work_handiwork': 3,
            'work_gathering': 1,
            'work_lumbering': 0,
            'work_mining': 0,
            'work_medicine': 0,
            'work_cooling': 0,
            'work_transporting': 1,
            'work_farming': 0,
            'active_skill_1': '공기 대포',
            'active_skill_2': '파워 샷',
            'active_skill_3': '얼음 칼날',
            'active_skill_4': '플라즈마 토네이도',
            'active_skill_5': '파워 폭탄',
            'active_skill_6': '눈보라 스파이크',
            'active_skill_7': '팰 폭발',
            'drops': '팰지움 파편',
            'nickname': '',
            'map_daytime': 1,
            'map_nighttime': 1
        },
        {
            'id': 64,
            'name_kor': '플로라디노',
            'description_kor': '한번 화를 내면 걷잡을 수 없을 정도로 분기탱천한다. 플로라디노의 꼬리를 밟다라는 말은 누군가의 격노를 샀다는 뜻이다.',
            'elements': 'Grass|Dragon',
            'partnerSkill_name': '꽃향기 감도는 용',
            'partnerSkill_describe': '등에 타고 이동할 수 있다. 탑승 중 풀 속성 공격이 강화된다.',
            'partnerSkill_needItem': '',
            'partnerSkill_needItemTechLevel': '',
            'partnerSkill_level': '',
            'stats_size': 'L',
            'stats_rarity': 6,
            'stats_health': 110,
            'stats_food': 6,
            'stats_meleeAttack': 90,
            'stats_attack': 85,
            'stats_defense': 90,
            'stats_workSpeed': 100,
            'stats_support': 150,
            'stats_captureRateCorrect': 1,
            'stats_maleProbability': 50,
            'stats_combiRank': 820,
            'stats_gold': 3240,
            'stats_slowWalkSpeed': 70,
            'stats_walkSpeed': 120,
            'stats_runSpeed': 700,
            'stats_rideSprintSpeed': 1030,
            'stats_transportSpeed': 335,
            'stats_stamina': 130,
            'work_kindling': 0,
            'work_watering': 0,
            'work_planting': 2,
            'work_generating_electricity': 0,
            'work_handiwork': 0,
            'work_gathering': 0,
            'work_lumbering': 2,
            'work_mining': 0,
            'work_medicine': 0,
            'work_cooling': 0,
            'work_transporting': 0,
            'work_farming': 0,
            'active_skill_1': '바람의 칼날',
            'active_skill_2': '꼬리 채찍',
            'active_skill_3': '용의 파장',
            'active_skill_4': '씨앗 지뢰',
            'active_skill_5': '용의 숨결',
            'active_skill_6': '가시덩굴',
            'active_skill_7': '태양 폭발',
            'drops': '밀 씨|당근 씨',
            'nickname': '',
            'map_daytime': 688,
            'map_nighttime': 688
        }
    ]
    
    # 기존 데이터 읽기
    with open(input_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        existing_data = list(reader)
        headers = reader.fieldnames
    
    # 새 데이터 추가
    all_data = existing_data + new_pals
    
    # 새 CSV 파일 쓰기
    with open(output_file, 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(all_data)
    
    print(f"✅ Successfully added 61-64 pals to {output_file}")
    print(f"Total pals: {len(all_data)}")

if __name__ == "__main__":
    main() 