import csv
import re

# 현재 CSV 파일 읽기
input_file = 'complete_1_to_48_pals.csv'
output_file = 'complete_1_to_56_pals.csv'

# 기존 데이터 로드
existing_data = []
with open(input_file, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        existing_data.append(row)

# 52-56번 팰 데이터 (정확한 필드명 사용)
new_pals = [
    {
        "id": "52",
        "name_kor": "소름냥이",
        "description_kor": "쥐구멍을 찾아다니며 무언가를 쫓고 있다. 몇 년에 걸친 관찰 결과 그것은 '소름'이라는 것이 밝혀졌다.",
        "elements": "무속성",
        "partnerSkill_name": "소름냥이의 실수",
        "partnerSkill_describe": "보유하고 있는 동안 무속성 팰의 공격력이 증가한다. 가끔 작업 중 아이템을 발견하기도 한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "stats_size": "S",
        "stats_rarity": "1",
        "stats_hp": "60",
        "stats_foodAmount": "150",
        "stats_melee": "100",
        "stats_shot": "70",
        "stats_defense": "70",
        "stats_support": "100",
        "stats_craftSpeed": "100",
        "stats_captureRateCorrect": "1.1",
        "stats_maleProb": "50",
        "price": "1460",
        "moveSpeed_slow": "70",
        "moveSpeed_walk": "110",
        "moveSpeed_run": "300",
        "workSuitability_handiwork": "1",
        "workSuitability_transport": "1",
        "workSuitability_mining": "1",
        "workSuitability_oilrig": "",
        "workSuitability_logging": "",
        "workSuitability_watering": "",
        "workSuitability_seeding": "",
        "workSuitability_generate": "",
        "workSuitability_gathering": "",
        "workSuitability_cooling": "",
        "workSuitability_farming": "",
        "workSuitability_medicine": "",
        "workSuitability_kindling": "",
        "activeSkillList_names": "공기 대포|윈드 커터|파워 샷|파워 폭탄|코큰트 불릿|윈드 블래스트|팰 폭발",
        "activeSkillList_powers": "25|30|35|70|150|80|150",
        "activeSkillList_elements": "무속성|풀속성|무속성|무속성|무속성|풀속성|무속성",
        "activeSkillList_cooldowns": "2|3|4|15|55|12|55",
        "dropItems_names": "양털|소름냥이의 털털털",
        "dropItems_probs": "100%|50%",
        "dropItems_quantities": "1|1",
        "breedCombiRank": "1540",
        "breedEggType": "얼어붙은 알",
        "foodAmount": "2"
    },
    {
        "id": "53",
        "name_kor": "모프링",
        "description_kor": "지면을 기어 다니며 미세 유기물을 섭취한다. 영양이 없는 건 잠시 후 배출한다. 걸레라 생각하고 청소에 활용하면 서로 윈윈.",
        "elements": "얼음",
        "partnerSkill_name": "복슬복슬",
        "partnerSkill_describe": "보유하고 있는 동안 모프킹의 스테이터스가 상승한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "stats_size": "XS",
        "stats_rarity": "1",
        "stats_hp": "60",
        "stats_foodAmount": "150",
        "stats_melee": "100",
        "stats_shot": "60",
        "stats_defense": "60",
        "stats_support": "100",
        "stats_craftSpeed": "100",
        "stats_captureRateCorrect": "1.1",
        "stats_maleProb": "50",
        "price": "1180",
        "moveSpeed_slow": "55",
        "moveSpeed_walk": "100",
        "moveSpeed_run": "250",
        "workSuitability_handiwork": "",
        "workSuitability_transport": "",
        "workSuitability_mining": "",
        "workSuitability_oilrig": "",
        "workSuitability_logging": "",
        "workSuitability_watering": "",
        "workSuitability_seeding": "",
        "workSuitability_generate": "",
        "workSuitability_gathering": "1",
        "workSuitability_cooling": "1",
        "workSuitability_farming": "",
        "workSuitability_medicine": "",
        "workSuitability_kindling": "",
        "activeSkillList_names": "공기 대포|얼음 미사일|얼음 칼날|파워 폭탄|빙산|서리 낀 입김|눈보라 스파이크",
        "activeSkillList_powers": "25|30|55|70|70|90|130",
        "activeSkillList_elements": "무속성|얼음|얼음|무속성|얼음|얼음|얼음",
        "activeSkillList_cooldowns": "2|3|10|15|15|22|45",
        "dropItems_names": "양털|모프링의 솜털",
        "dropItems_probs": "100%|50%",
        "dropItems_quantities": "1|1",
        "breedCombiRank": "1300",
        "breedEggType": "얼어붙은 알",
        "foodAmount": "2"
    },
    {
        "id": "54",
        "name_kor": "모프킹",
        "description_kor": "동면 중엔 거대한 털 뭉치 속에 대량의 모프링이 숨어 있다. 과거 최대 기록은 무려 101마리.",
        "elements": "얼음",
        "partnerSkill_name": "복슬복슬 끝판왕",
        "partnerSkill_describe": "등에 타고 이동할 수 있다. 함께 싸우는 동안 보유하고 있는 모프링의 개체수가 많을수록 스테이터스가 상승한다.",
        "partnerSkill_needItem": "모프킹 안장",
        "partnerSkill_needItemTechLevel": "14",
        "partnerSkill_level": "1",
        "stats_size": "L",
        "stats_rarity": "6",
        "stats_hp": "100",
        "stats_foodAmount": "225",
        "stats_melee": "100",
        "stats_shot": "90",
        "stats_defense": "90",
        "stats_support": "100",
        "stats_craftSpeed": "100",
        "stats_captureRateCorrect": "1",
        "stats_maleProb": "50",
        "price": "6400",
        "moveSpeed_slow": "60",
        "moveSpeed_walk": "120",
        "moveSpeed_run": "650",
        "workSuitability_handiwork": "",
        "workSuitability_transport": "",
        "workSuitability_mining": "",
        "workSuitability_oilrig": "",
        "workSuitability_logging": "",
        "workSuitability_watering": "",
        "workSuitability_seeding": "",
        "workSuitability_generate": "",
        "workSuitability_gathering": "2",
        "workSuitability_cooling": "2",
        "workSuitability_farming": "",
        "workSuitability_medicine": "",
        "workSuitability_kindling": "",
        "activeSkillList_names": "파워 샷|얼음 미사일|얼음 칼날|빙산|서리 낀 입김|팰 폭발|눈보라 스파이크",
        "activeSkillList_powers": "35|30|55|70|90|150|130",
        "activeSkillList_elements": "무속성|얼음|얼음|얼음|얼음|무속성|얼음",
        "activeSkillList_cooldowns": "4|3|10|15|22|55|45",
        "dropItems_names": "양털",
        "dropItems_probs": "100%",
        "dropItems_quantities": "3-5",
        "breedCombiRank": "410",
        "breedEggType": "얼어붙은 대형 알",
        "foodAmount": "3"
    },
    {
        "id": "55",
        "name_kor": "베비뇽",
        "description_kor": "몸을 둥글게 말아 엄청난 속도로 회전 이동할 수 있다. 옛날 사람들은 길들인 베비뇽에게 우유 주머니를 달아 방목하며 그 회전력으로 버터를 만들었다.",
        "elements": "얼음|용",
        "partnerSkill_name": "꿈틀꿈틀 족제비",
        "partnerSkill_describe": "등에 타고 이동할 수 있다. 탑승 중 플레이어의 공격이 용 속성으로 변화한다.",
        "partnerSkill_needItem": "베비뇽 안장",
        "partnerSkill_needItemTechLevel": "13",
        "partnerSkill_level": "1",
        "stats_size": "M",
        "stats_rarity": "4",
        "stats_hp": "90",
        "stats_foodAmount": "225",
        "stats_melee": "100",
        "stats_shot": "80",
        "stats_defense": "80",
        "stats_support": "100",
        "stats_craftSpeed": "100",
        "stats_captureRateCorrect": "1",
        "stats_maleProb": "50",
        "price": "3450",
        "moveSpeed_slow": "100",
        "moveSpeed_walk": "180",
        "moveSpeed_run": "750",
        "workSuitability_handiwork": "",
        "workSuitability_transport": "",
        "workSuitability_mining": "",
        "workSuitability_oilrig": "",
        "workSuitability_logging": "",
        "workSuitability_watering": "",
        "workSuitability_seeding": "",
        "workSuitability_generate": "",
        "workSuitability_gathering": "1",
        "workSuitability_cooling": "1",
        "workSuitability_farming": "",
        "workSuitability_medicine": "",
        "workSuitability_kindling": "",
        "activeSkillList_names": "얼음 미사일|용 대포|로켓 태클|용의 파장|얼음 칼날|용의 숨결|서리 낀 입김|용의 운석",
        "activeSkillList_powers": "30|30|50|55|55|70|90|150",
        "activeSkillList_elements": "얼음|용|용|용|얼음|용|얼음|용",
        "activeSkillList_cooldowns": "3|2|6|10|10|15|22|55",
        "dropItems_names": "가죽",
        "dropItems_probs": "100%",
        "dropItems_quantities": "2-3",
        "breedCombiRank": "800",
        "breedEggType": "얼어붙은 알",
        "foodAmount": "3"
    },
    {
        "id": "56",
        "name_kor": "썬더콘",
        "description_kor": "예전엔 번개 신의 사자로 여겨져 사람들이 건드리지 않았다. 하지만 낙뢰에 맞아 사망하는 모습이 목격된 뒤로 신앙이 무너지며 보이는 족족 잡혔다.",
        "elements": "번개",
        "partnerSkill_name": "질풍과 우레",
        "partnerSkill_describe": "등에 타고 이동할 수 있다. 탑승 중 플레이어의 공격이 번개 속성으로 변화한다.",
        "partnerSkill_needItem": "썬더콘 안장",
        "partnerSkill_needItemTechLevel": "14",
        "partnerSkill_level": "1",
        "stats_size": "M",
        "stats_rarity": "5",
        "stats_hp": "80",
        "stats_foodAmount": "350",
        "stats_melee": "110",
        "stats_shot": "105",
        "stats_defense": "105",
        "stats_support": "100",
        "stats_craftSpeed": "100",
        "stats_captureRateCorrect": "0.9",
        "stats_maleProb": "50",
        "price": "4280",
        "moveSpeed_slow": "80",
        "moveSpeed_walk": "130",
        "moveSpeed_run": "720",
        "workSuitability_handiwork": "",
        "workSuitability_transport": "",
        "workSuitability_mining": "",
        "workSuitability_oilrig": "",
        "workSuitability_logging": "1",
        "workSuitability_watering": "",
        "workSuitability_seeding": "",
        "workSuitability_generate": "2",
        "workSuitability_gathering": "",
        "workSuitability_cooling": "",
        "workSuitability_farming": "",
        "workSuitability_medicine": "",
        "workSuitability_kindling": "",
        "activeSkillList_names": "스파크 샷|전기 파장|질풍뇌격|고정식 레이저|라인 썬더|트라이 썬더|번개 일격|전기 볼트",
        "activeSkillList_powers": "30|40|60|70|75|90|120|150",
        "activeSkillList_elements": "번개|번개|번개|번개|번개|번개|번개|번개",
        "activeSkillList_cooldowns": "2|4|8|15|16|22|40|55",
        "dropItems_names": "가죽|발전 기관|뿔",
        "dropItems_probs": "100%|100%|50%",
        "dropItems_quantities": "2|1|1",
        "breedCombiRank": "680",
        "breedEggType": "찌릿찌릿한 대형 알",
        "foodAmount": "5"
    }
]

# 모든 데이터 합치기
all_data = existing_data + new_pals

# 새 CSV 파일로 저장
with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(all_data)

print(f"✅ 완료! {output_file} 저장됨")
print(f"총 {len(all_data)}개 팰 (기존 {len(existing_data)}개 + 새로 추가된 {len(new_pals)}개)")
print(f"컬럼 수: {len(fieldnames)}") 