import csv
import re

# 현재 CSV 파일 읽기
input_file = 'complete_1_to_46_pals.csv'
output_file = 'complete_1_to_48_pals.csv'

# 기존 데이터 로드
existing_data = []
with open(input_file, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        existing_data.append(row)

# 44-48번 팰 데이터 (정확한 필드명 사용)
new_pals = [
    {
        "id": "44",
        "name_kor": "마스크로우",
        "description_kor": "원래 드넓은 창공을 자유로이 날아다녔으나 질풍수리와(과) 싸움에서 패배해 하늘을 빼앗기고 밤에 숨죽인 채 살게 됐다.",
        "elements": "어둠",
        "partnerSkill_name": "원격 부리 공격",
        "partnerSkill_describe": "발동하면 목표로 삼은 적을 향해 높은 위력의 팬텀의 공격(으)로 공격한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "stats_size": "M",
        "stats_rarity": "3",
        "stats_health": "75",
        "stats_food": "5",
        "stats_meleeAttack": "80",
        "stats_attack": "95",
        "stats_defense": "80",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "1.0",
        "stats_maleProbability": "50",
        "stats_combiRank": "1080",
        "stats_goldCoin": "1840",
        "stats_egg": "암흑의 알",
        "stats_code": "Cawgnito",
        "movement_slowWalkSpeed": "170",
        "movement_walkSpeed": "170",
        "movement_runSpeed": "920",
        "movement_rideSprintSpeed": "1200",
        "movement_transportSpeed": "545",
        "level60_health": "3100–3782",
        "level60_attack": "563–694",
        "level60_defense": "440–557",
        "activeSkills": "공기 대포(Lv.1)|암흑구(Lv.7)|팬텀의 공격(Lv.15)|그림자 폭발(Lv.22)|유령의 불꽃(Lv.30)|악몽의 구체(Lv.40)|어둠의 레이저(Lv.50)",
        "activeSkills_count": "7",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "뼈(2–4, 100%)|독샘(2, 100%)|작은 팰 영혼(1, 1%)",
        "drops_count": "3",
        "workSuitabilities": "벌목(LV.1)",
        "workSuitabilities_count": "1",
        "tribes": "마스크로우",
        "tribes_count": "1",
        "spawners": "마스크로우(Lv. 30–34)",
        "spawners_count": "1"
    },
    {
        "id": "45",
        "name_kor": "도마맨",
        "description_kor": "일어선 모습에 이상한 집착을 보인다. 항상 제일 멋진 자세를 연구하며 거울을 주면 하루 종일 자세만 궁리한다.",
        "elements": "어둠",
        "partnerSkill_name": "제6감",
        "partnerSkill_describe": "발동하면 6번째 감각을 활용해 가까이 있는 던전의 위치를 탐지할 수 있다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "stats_size": "S",
        "stats_rarity": "2",
        "stats_health": "80",
        "stats_food": "3",
        "stats_meleeAttack": "90",
        "stats_attack": "80",
        "stats_defense": "50",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "1.0",
        "stats_maleProbability": "50",
        "stats_combiRank": "1120",
        "stats_goldCoin": "1720",
        "stats_egg": "암흑의 알",
        "stats_code": "Leezpunk",
        "movement_slowWalkSpeed": "140",
        "movement_walkSpeed": "140",
        "movement_runSpeed": "600",
        "movement_rideSprintSpeed": "800",
        "movement_transportSpeed": "270",
        "level60_health": "3425–4205",
        "level60_attack": "490–607",
        "level60_defense": "293–366",
        "activeSkills": "독 사격(Lv.1)|암흑구(Lv.7)|그림자 폭발(Lv.15)|유령의 불꽃(Lv.22)|악몽의 구체(Lv.30)|파이어 브레스(Lv.40)|어둠의 레이저(Lv.50)",
        "activeSkills_count": "7",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "구리 열쇠(1, 100%)|은 열쇠(1, 1%)|도마맨의 볏(1, 50%)",
        "drops_count": "3",
        "workSuitabilities": "수작업(LV.1)|운반(LV.1)|채집(LV.1)",
        "workSuitabilities_count": "3",
        "tribes": "도마맨",
        "tribes_count": "1",
        "spawners": "도마맨(Lv. 30–34)",
        "spawners_count": "1"
    },
    {
        "id": "46",
        "name_kor": "달서니",
        "description_kor": "머리의 뿔은 달빛을 받아야 자란다. 태양을 못 견디는 건 아니지만 햇빛을 쬐는 동안에는 뿔이 근질거린다.",
        "elements": "어둠",
        "partnerSkill_name": "어둠 속에 번쩍이는 발톱날",
        "partnerSkill_describe": "발동하면 목표로 삼은 적을 향해 높은 위력의 점프 할퀴기(으)로 공격한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "stats_size": "M",
        "stats_rarity": "3",
        "stats_health": "80",
        "stats_food": "5",
        "stats_meleeAttack": "130",
        "stats_attack": "100",
        "stats_defense": "80",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "1.0",
        "stats_maleProbability": "50",
        "stats_combiRank": "950",
        "stats_goldCoin": "2400",
        "stats_egg": "암흑의 알",
        "stats_code": "Loupmoon",
        "movement_slowWalkSpeed": "175",
        "movement_walkSpeed": "175",
        "movement_runSpeed": "600",
        "movement_rideSprintSpeed": "800",
        "movement_transportSpeed": "375",
        "level60_health": "3425–4205",
        "level60_attack": "612–758",
        "level60_defense": "440–557",
        "activeSkills": "암흑구(Lv.1)|점프 할퀴기(Lv.7)|그림자 폭발(Lv.15)|얼음 칼날(Lv.22)|유령의 불꽃(Lv.30)|악몽의 구체(Lv.40)|어둠의 레이저(Lv.50)",
        "activeSkills_count": "7",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "뼈(1, 100%)",
        "drops_count": "1",
        "workSuitabilities": "수작업(LV.2)",
        "workSuitabilities_count": "1",
        "tribes": "달서니",
        "tribes_count": "1",
        "spawners": "달서니(Lv. 32–36)",
        "spawners_count": "1"
    },
    {
        "id": "47",
        "name_kor": "질풍수리",
        "description_kor": "사람을 낚아챈 채로도 잘 날아다닌다. 하지만 지치면 주저 없이 놓아버리므로 추락사 사고가 끊이지 않는다.",
        "elements": "무속성",
        "partnerSkill_name": "질풍의 활공",
        "partnerSkill_describe": "보유하고 있는 동안 글라이더의 성능이 변화한다. 활공 속도가 증가하며, 오른손으로 사격이 가능해진다.",
        "partnerSkill_needItem": "질풍수리의 장갑",
        "partnerSkill_needItemTechLevel": "23",
        "partnerSkill_level": "1",
        "stats_size": "M",
        "stats_rarity": "2",
        "stats_health": "75",
        "stats_food": "4",
        "stats_meleeAttack": "120",
        "stats_attack": "85",
        "stats_defense": "60",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "1.0",
        "stats_maleProbability": "50",
        "stats_combiRank": "1030",
        "stats_goldCoin": "2010",
        "stats_egg": "평범한 알",
        "stats_code": "Galeclaw",
        "movement_slowWalkSpeed": "200",
        "movement_walkSpeed": "200",
        "movement_runSpeed": "600",
        "movement_rideSprintSpeed": "700",
        "movement_transportSpeed": "400",
        "level60_health": "3262–3993",
        "level60_attack": "563–702",
        "level60_defense": "342–430",
        "activeSkills": "활공 할퀴기(Lv.1)|공기 대포(Lv.7)|모래 돌풍(Lv.15)|바람의 칼날(Lv.22)|모래 폭풍(Lv.30)|초록 폭풍(Lv.40)|팰 폭발(Lv.50)",
        "activeSkills_count": "7",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "질풍수리의 살코기(1, 100%)|가죽(1, 100%)",
        "drops_count": "2",
        "workSuitabilities": "채집(LV.2)",
        "workSuitabilities_count": "1",
        "tribes": "질풍수리",
        "tribes_count": "1",
        "spawners": "질풍수리(Lv. 32–36)",
        "spawners_count": "1"
    },
    {
        "id": "48",
        "name_kor": "로빈몽",
        "description_kor": "숲에서 수렵 생활을 하는, 사람과 비슷한 성질의 팰. 아주 먼 옛날 사람과 다른 계통으로 갈라졌다고 여겨지며 팰의 정체를 밝혀줄 열쇠일지도 모른다.",
        "elements": "풀",
        "partnerSkill_name": "매의 눈",
        "partnerSkill_describe": "함께 싸우는 동안 플레이어가 약점 부위에 주는 피해량이 증가한다.",
        "partnerSkill_needItem": "",
        "partnerSkill_needItemTechLevel": "0",
        "partnerSkill_level": "1",
        "stats_size": "M",
        "stats_rarity": "5",
        "stats_health": "90",
        "stats_food": "3",
        "stats_meleeAttack": "100",
        "stats_attack": "105",
        "stats_defense": "80",
        "stats_workSpeed": "100",
        "stats_support": "100",
        "stats_captureRateCorrect": "1.0",
        "stats_maleProbability": "50",
        "stats_combiRank": "1020",
        "stats_goldCoin": "2050",
        "stats_egg": "신록의 알",
        "stats_code": "Robinquill",
        "movement_slowWalkSpeed": "100",
        "movement_walkSpeed": "100",
        "movement_runSpeed": "600",
        "movement_rideSprintSpeed": "750",
        "movement_transportSpeed": "400",
        "level60_health": "3750–4627",
        "level60_attack": "611–765",
        "level60_defense": "440–557",
        "activeSkills": "바람의 칼날(Lv.1)|파워 샷(Lv.7)|스나이핑 샷(Lv.15)|씨앗 지뢰(Lv.22)|초록 폭풍(Lv.30)|가시덩굴(Lv.40)|태양 폭발(Lv.50)",
        "activeSkills_count": "7",
        "passiveSkills": "",
        "passiveSkills_count": "0",
        "drops": "밀 씨(1–2, 50%)|화살(2–4, 100%)|감자 종자(1, 50%)",
        "drops_count": "3",
        "workSuitabilities": "벌목(LV.1)|수작업(LV.2)|운반(LV.2)|파종(LV.1)|채집(LV.2)|제약(LV.1)",
        "workSuitabilities_count": "6",
        "tribes": "로빈몽",
        "tribes_count": "1",
        "spawners": "로빈몽(Lv. 34–38)",
        "spawners_count": "1"
    }
]

# 새로운 CSV 파일 생성
with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    
    # 기존 데이터 쓰기
    writer.writerows(existing_data)
    
    # 새로운 팰 데이터 쓰기
    writer.writerows(new_pals)

print(f"✅ 완료! {output_file} 저장됨")
print(f"총 {len(existing_data) + len(new_pals)}개 팰")
print(f"- 기존 데이터: {len(existing_data)}개")  
print(f"- 새로 추가 44-48번: {len(new_pals)}개")
print(f"컬럼 수: {len(fieldnames)}") 